language: node_js
node_js:
  - stable
  - 14
  - 12
  - 10

before_install:
- npm install -g typescript

install:
  - npm ci

script:
- npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  