language: node_js
node_js:
  - stable
  - 10
  - 8
  - 6

before_install:
- npm install -g typescript

install:
  - npm install

script:
- npm test

cache:
  directories:
    - node_modules

after_success:
  - bash <(curl -s https://codecov.io/bash)
  